name: Deploy Multi-Environment

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.repository }}-deploy-dev
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Testes unitários
        run: |
          dotnet test --no-build --verbosity normal

      - name: SSH Deploy DEV
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_DEV_HOST }}
          username: ${{ secrets.VPS_DEV_USER }}
          key: ${{ secrets.VPS_DEV_SSH_KEY }}
          script: |
            set -e
            cd deploy/dev/

            cd ./payments-api-core
            git fetch origin && git checkout develop && git pull

            cd ../infra
            git fetch origin && git checkout develop && git pull

            cd ./APIs
            docker compose stop payments-api-dev || true
            docker compose rm -f payments-api-dev || true
            docker rmi apis-payments-api-dev:latest || true

            docker compose build

            if docker compose up -d; then
              echo "Deploy DEV com sucesso! Salvando imagem de backup..."
              docker tag apis-payments-api-dev:latest apis-payments-api-dev-backup:latest
            else
              echo "Erro no deploy DEV. Rollback iniciado..."
              docker compose down || true
              docker tag apis-payments-api-dev-backup:latest apis-payments-api-dev:latest
              docker run -d --name payments-api-dev apis-payments-api-dev-backup:latest
              echo "Rollback DEV concluído."
              exit 1
            fi
          debug: true

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.repository }}-deploy-prod
      cancel-in-progress: false
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://seu-site-prod.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Testes unitários
        run: |
          dotnet test --no-build --verbosity normal

      - name: SSH Deploy PROD
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_PROD_HOST }}
          username: ${{ secrets.VPS_PROD_USER }}
          key: ${{ secrets.VPS_PROD_SSH_KEY }}
          script: |
            set -e
            cd deploy/prod/

            cd ./payments-api-core
            git fetch origin && git checkout main && git pull

            cd ../infra
            git fetch origin && git checkout main && git pull

            cd ./APIs
            docker compose stop payments-api || true
            docker compose rm -f payments-api || true
            docker rmi apis-payments-api:latest || true

            docker compose build

            if docker compose up -d; then
              echo "Deploy PROD com sucesso! Salvando imagem de backup..."
              docker tag apis-payments-api:latest apis-payments-api-backup:latest
            else
              echo "Erro no deploy PROD. Rollback iniciado..."
              docker compose down || true
              docker tag apis-payments-api-backup:latest apis-payments-api:latest
              docker run -d --name payments-api apis-payments-api-backup:latest
              echo "Rollback PROD concluído."
              exit 1
            fi
